CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(100) NOT NULL,
  "phone_number" varchar(20) UNIQUE NOT NULL,
  "region" varchar(50) NOT NULL,
  "city_town" varchar(50) NOT NULL,
  "profile_photo_url" text,
  "pin_hash" varchar(255) NOT NULL,
  "phone_verified" boolean DEFAULT false,
  "is_suspended" boolean DEFAULT false,
  "is_deactivated" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "seller_profiles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "seller_type" varchar(50) NOT NULL,
  "business_name" varchar(100),
  "market_hub" varchar(100) NOT NULL,
  "business_description" text NOT NULL,
  "verification_status" varchar(20) DEFAULT 'UNVERIFIED',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "otp_verifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone_number" varchar(20) NOT NULL,
  "otp_code" varchar(6) NOT NULL,
  "expires_at" timestamp NOT NULL,
  "is_used" boolean DEFAULT false
);

CREATE TABLE "listings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" integer,
  "product_name" varchar(150) NOT NULL,
  "category" varchar(50) NOT NULL,
  "description" text NOT NULL,
  "quantity" integer NOT NULL,
  "unit_of_measurement" varchar(50),
  "original_price" decimal(10,2) NOT NULL,
  "current_price" decimal(10,2) NOT NULL,
  "is_expiry_sensitive" boolean DEFAULT false,
  "expiry_date" date,
  "clearance_end_date" date NOT NULL,
  "discount_step_percent" decimal(5,2) NOT NULL,
  "discount_interval_days" integer NOT NULL,
  "last_discount_applied_at" timestamp,
  "minimum_acceptable_price" decimal(10,2) NOT NULL,
  "listing_status" varchar(20) DEFAULT 'ACTIVE',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "listing_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "listing_id" integer,
  "image_url" text NOT NULL
);

CREATE TABLE "saved_listings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "listing_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "purchase_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "listing_id" integer,
  "buyer_user_id" integer,
  "seller_user_id" integer,
  "conversation_id" integer,
  "requested_quantity" integer NOT NULL,
  "status" varchar(20) DEFAULT 'PENDING',
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "conversations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "listing_id" integer,
  "buyer_user_id" integer,
  "seller_user_id" integer,
  "status" varchar(20) DEFAULT 'ACTIVE',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" integer,
  "sender_user_id" integer,
  "message_content" text NOT NULL,
  "is_seen" boolean DEFAULT false,
  "seen_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchase_request_id" integer,
  "listing_id" integer,
  "buyer_user_id" integer,
  "seller_user_id" integer,
  "quantity" integer NOT NULL,
  "fulfillment_method" varchar(50),
  "status" varchar(30) DEFAULT 'PENDING_FULFILLMENT',
  "otp_hash" varchar(255),
  "otp_generated_at" timestamp,
  "completed_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "transaction_evidence" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" integer,
  "image_url" text NOT NULL,
  "uploaded_by" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "fulfillments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchase_request_id" integer,
  "status" varchar(30) DEFAULT 'PENDING',
  "otp_code" varchar(6),
  "otp_generated_at" timestamp,
  "delivered_at" timestamp,
  "completed_at" timestamp,
  "completion_method" varchar(20),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "title" varchar(150) NOT NULL,
  "message" text NOT NULL,
  "category" varchar(50) NOT NULL,
  "priority" varchar(10) DEFAULT 'NORMAL',
  "status" varchar(10) DEFAULT 'UNREAD',
  "target_type" varchar(50),
  "target_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "activity_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "activity_type" varchar(100) NOT NULL,
  "description" text,
  "related_entity_type" varchar(50),
  "related_entity_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "admin_users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(150) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" varchar(20) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporter_user_id" integer,
  "report_type" varchar(50) NOT NULL,
  "target_id" integer NOT NULL,
  "reason" text NOT NULL,
  "status" varchar(20) DEFAULT 'PENDING',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" integer,
  "action_type" varchar(100) NOT NULL,
  "target_type" varchar(50) NOT NULL,
  "target_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_settings" (
  "user_id" integer PRIMARY KEY,
  "notifications_enabled" boolean DEFAULT true,
  "message_notifications" boolean DEFAULT true,
  "request_notifications" boolean DEFAULT true,
  "verification_notifications" boolean DEFAULT true,
  "transaction_notifications" boolean DEFAULT true,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "device_identifier" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "expires_at" timestamp NOT NULL
);

ALTER TABLE "seller_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "listings" ADD FOREIGN KEY ("seller_id") REFERENCES "seller_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "listing_images" ADD FOREIGN KEY ("listing_id") REFERENCES "listings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saved_listings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saved_listings" ADD FOREIGN KEY ("listing_id") REFERENCES "listings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_requests" ADD FOREIGN KEY ("listing_id") REFERENCES "listings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_requests" ADD FOREIGN KEY ("buyer_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_requests" ADD FOREIGN KEY ("seller_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversations" ADD FOREIGN KEY ("listing_id") REFERENCES "listings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversations" ADD FOREIGN KEY ("buyer_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversations" ADD FOREIGN KEY ("seller_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transactions" ADD FOREIGN KEY ("purchase_request_id") REFERENCES "purchase_requests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transactions" ADD FOREIGN KEY ("listing_id") REFERENCES "listings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transactions" ADD FOREIGN KEY ("buyer_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transactions" ADD FOREIGN KEY ("seller_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transaction_evidence" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transaction_evidence" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fulfillments" ADD FOREIGN KEY ("purchase_request_id") REFERENCES "purchase_requests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "activity_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reports" ADD FOREIGN KEY ("reporter_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("admin_user_id") REFERENCES "admin_users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_settings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
