# App
spring.application.name=backend

# Database - Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-old-leaf-ai9oxcva.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xSCyral8Q2XB
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=clearstock_secret_key_2026_codequest_group16
jwt.expiration=86400000

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=clearstock101@gmail.com
spring.mail.password=rbiftmqtdtbznleh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false